name: ci

env:
  CMAKE_BUILD_TYPE: Release
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  CTEST_NO_TESTS_ACTION: error

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.f90"
      - "**.py"
      - ".github/workflows/ci.yml"


jobs:

  core:
    strategy:
      matrix:
        os: [ubuntu-24.04]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        include:
        - os: macos-latest
          python-version: "3.10"

    runs-on: ${{ matrix.os }}

    env:
      FC: gfortran-14

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install .[tests,lint]

    - run: flake8
    - run: mypy

    - name: Build Lowtran, check that it can be imported by Python
      run: python -c "import lowtran; lowtran.check()"

    - run: pytest

    - run: cmake --workflow --preset default

  windows:
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc-fortran
    # Github actions Gfortran in default image is messed up.

    - name: Put MSYS2_MinGW64 on PATH
      run: echo "${{ runner.temp }}/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - uses: actions/checkout@v4

    - run: python -m pip install .[tests,lint]

    - run: flake8
    - run: mypy

    - name: Build Lowtran, check that it can be imported by Python
      run: python -c "import lowtran; lowtran.check()"

    - run: pytest -v

    - run: cmake -B build
      env:
        CMAKE_GENERATOR: "MinGW Makefiles"

    - run: cmake --build build
    - run: ctest --test-dir build --preset default
